/* Keyword tags scattered around the landing page, tilted, taken from the SKILLS section of
 * the résumé (see keywords.generated.ts — regenerated by `npm run corpus`).
 *
 * Four decisions worth stating.
 *
 * The positions are hand-placed, not random. Random scatter looks the same on average and
 * occasionally drops a tag straight onto the composer, and a layout that is broken one visit
 * in ten is broken. Each slot is a percentage of the container with a fixed tilt, arranged in
 * two bands down the left and right of the centre column.
 *
 * Hand-placed is still not enough, so a tag also hides itself when it measures an overlap with
 * the centre column. The coordinates were checked at four viewport widths and a tag still
 * landed on the suggestion chips, because the chips wrap differently with different text and
 * the seed questions are not fixed forever. Measuring beats predicting.
 *
 * They move on separate planes. The pointer shifts the whole field, each tag by an amount set
 * by its own depth, so the set has parallax instead of sliding as one sheet. That needs two
 * transform channels: the plane owns `translate` for parallax, the button inside owns
 * `translate` for its idle drift. One element cannot take the same property from a keyframe
 * and a pointer handler at once.
 *
 * They are buttons. A decoration that answers when you click it stops being decoration —
 * clicking "HTLC atomic swaps" asks about HTLC atomic swaps, which is also the fastest way to
 * discover that arbitrary questions work at all. They stay quiet until hovered so they read
 * as texture first and as an invitation second.
 */

import { useEffect, useRef } from "react";
import type React from "react";
import { RESUME_KEYWORDS } from "./keywords.generated";

interface Slot {
  /** Percentage from the left edge of the landing area. */
  x: number;
  /** Percentage from the top. */
  y: number;
  /** Degrees. */
  rot: number;
  /** Relative size, 0.9–1.1. */
  scale?: number;
  /** Parallax plane: 0.4 is far away and barely moves, 1 is near and moves most. */
  depth?: number;
}

type TagStyle = React.CSSProperties & Record<`--${string}`, string>;

/* Each tag drifts on its own loop. The numbers are the point of this: 16–26 seconds for one
 * circuit of 5–9 pixels is slow enough that you never catch a tag moving, only notice the
 * page is not quite still. Shared timings would make the whole set breathe in unison, which
 * reads as a loading state. Derived from the index so the arrangement stays deterministic. */
function drift(i: number): TagStyle {
  const dx = 5 + ((i * 3) % 5);
  const dy = 4 + ((i * 5) % 4);
  return {
    "--dx": `${i % 2 ? dx : -dx}px`,
    "--dy": `${i % 3 ? dy : -dy}px`,
    "--dur": `${16 + ((i * 7) % 11)}s`,
    "--lag": `-${(i * 1.9).toFixed(1)}s`,
  };
}

/* Left band, right band, and a few along the top and bottom. Nothing between x 26 and 74,
 * which is where the heading, the composer and the suggestion chips live. Depth alternates so
 * that neighbouring tags travel by visibly different amounts. */
const SLOTS: Slot[] = [
  // Left band. Slots level with the centre column stay inside x 16, so even a long keyword
  // cannot reach the composer.
  { x: 6, y: 12, rot: -7, depth: 0.5 },
  { x: 5, y: 25, rot: 5, scale: 1.08, depth: 1 },
  { x: 3, y: 37, rot: 8, depth: 0.7 },
  { x: 4, y: 48, rot: -4, depth: 0.4 },
  { x: 6, y: 59, rot: 6, scale: 0.94, depth: 0.85 },
  { x: 12, y: 70, rot: -8, depth: 0.55 },
  { x: 8, y: 79, rot: 3, depth: 0.95 },

  // Right band, anchored on the right edge. Pulled to x 96–97 across the centre column's
  // height for the same reason, and only shorter keywords are placed there.
  { x: 82, y: 11, rot: 6, depth: 0.6 },
  { x: 96, y: 25, rot: -5, scale: 1.06, depth: 1 },
  { x: 97, y: 36, rot: -8, depth: 0.45 },
  { x: 96, y: 47, rot: 4, depth: 0.8 },
  { x: 97, y: 58, rot: -3, scale: 0.95, depth: 0.5 },
  { x: 92, y: 69, rot: 7, depth: 0.9 },
  { x: 82, y: 78, rot: -6, depth: 0.65 },

  /* Above the heading and below the chips, where the column is clear. The lowest row used to
     sit at 91 and 92, hard against the bottom edge, which left the set trailing away from the
     content instead of framing it. The chips end near 66%, so 85 is as high as these can go. */
  { x: 33, y: 7, rot: -4, scale: 0.94, depth: 0.75 },
  { x: 57, y: 5, rot: 5, depth: 0.45 },
  { x: 30, y: 85, rot: 6, depth: 0.85 },
  { x: 62, y: 86, rot: -5, scale: 0.96, depth: 0.6 },
];

/* Which keywords go in which slot. Fixed rather than shuffled: the page should look the same
 * every visit, and the interesting terms belong in the slots nearest the eye. */
const ORDER = [
  // Ordered to match SLOTS: the short terms take the slots level with the centre column,
  // where there is least room, and the long ones sit above or below it.
  "Rust", // left, high
  "HTLC atomic swaps", // left, above the heading line
  "libvirt", // left, level with the heading
  "strace", // left, level with the composer
  "Virtio", // left, level with the chips
  "Model Context Protocol", // left, below
  "UTXO ledgers", // left, lowest
  "Linux kernel internals", // right, high
  "P2P sync and reorg handling", // right, above the heading line
  "QEMU/KVM", // right, level with the heading
  "gdb", // right, level with the composer
  "perf", // right, level with the chips
  "QEMU Guest Agent", // right, below
  "agent tool design", // right, lowest
  "Python", // above the heading
  "TypeScript",
  "V2V migration", // below the chips
  "LLM-as-judge",
];

/** Parallax travel of the nearest plane, in pixels, from the centre to the edge of the page. */
const REACH = 18;

/**
 * Pointer parallax for the whole field, and the runtime overlap check.
 *
 * One rAF loop writes two custom properties on the container, and each plane multiplies them
 * by its own depth in CSS. Eighteen tags therefore cost one style write per frame instead of
 * eighteen, and nothing re-renders: React never sees the pointer.
 */
function useParallax(container: React.RefObject<HTMLDivElement | null>) {
  useEffect(() => {
    const host = container.current;
    if (!host) return;

    /* Hide any tag that overlaps what the centre column actually occupies on this screen.
     * Runs after layout and on every resize, because whether a tag fits depends on how the
     * suggestion chips wrapped, which depends on their text. */
    const cull = () => {
      const zones = [".h1", ".composer", ".suggestions"]
        .map((sel) => document.querySelector(sel)?.getBoundingClientRect())
        .filter((r): r is DOMRect => Boolean(r));

      for (const plane of host.querySelectorAll<HTMLElement>(".sticker-plane")) {
        // Measure unhidden, or a tag hidden once could never come back after a resize.
        plane.style.visibility = "";
        const r = plane.getBoundingClientRect();
        const pad = 10; // air, so a tag never looks like it is touching the column
        const clash = zones.some(
          (z) =>
            r.right + pad > z.left &&
            r.left - pad < z.right &&
            r.bottom + pad > z.top &&
            r.top - pad < z.bottom,
        );
        if (clash || r.left < 0 || r.right > window.innerWidth) {
          plane.style.visibility = "hidden";
        }
      }
    };

    cull();
    const ro = new ResizeObserver(cull);
    ro.observe(document.body);
    const stopCull = () => ro.disconnect();

    // No pointer to follow, or the visitor asked for less motion. The tags still cull.
    if (
      window.matchMedia("(hover: none)").matches ||
      window.matchMedia("(prefers-reduced-motion: reduce)").matches
    ) {
      return stopCull;
    }

    let atX = 0;
    let atY = 0;
    let toX = 0;
    let toY = 0;
    let raf = 0;

    const loop = () => {
      /* Eased at 0.12, the same figure the wordmark sheen uses, so the field settles behind
       * the cursor rather than snapping to it and the two movements feel like one hand. */
      atX += (toX - atX) * 0.12;
      atY += (toY - atY) * 0.12;
      host.style.setProperty("--px", `${atX.toFixed(2)}px`);
      host.style.setProperty("--py", `${atY.toFixed(2)}px`);
      raf =
        Math.abs(toX - atX) > 0.05 || Math.abs(toY - atY) > 0.05
          ? requestAnimationFrame(loop)
          : 0;
    };

    const onPointer = (e: PointerEvent) => {
      /* Negated, so the field slides against the pointer. Moving with it reads as dragging
       * the page around; moving against it reads as looking past something nearer. */
      toX = -((e.clientX / window.innerWidth) * 2 - 1) * REACH;
      toY = -((e.clientY / window.innerHeight) * 2 - 1) * REACH;
      if (!raf) raf = requestAnimationFrame(loop);
    };

    window.addEventListener("pointermove", onPointer, { passive: true });
    return () => {
      window.removeEventListener("pointermove", onPointer);
      if (raf) cancelAnimationFrame(raf);
      stopCull();
    };
  }, [container]);
}

export function Stickers({ onPick }: { onPick: (question: string) => void }) {
  const host = useRef<HTMLDivElement | null>(null);
  useParallax(host);

  const available = new Set<string>(RESUME_KEYWORDS);
  // Anything in ORDER that has left the résumé is dropped; anything new fills the gaps, so a
  // changed SKILLS section degrades into a different arrangement rather than blank slots.
  const chosen = [
    ...ORDER.filter((k) => available.has(k)),
    ...RESUME_KEYWORDS.filter((k) => !ORDER.includes(k)),
  ].slice(0, SLOTS.length);

  return (
    <div className="stickers" ref={host} aria-label="Topics from his résumé">
      {chosen.map((word, i) => {
        const slot = SLOTS[i]!;
        const plane: TagStyle = {
          /* Right-band tags anchor on their right edge so a long keyword grows inward
             instead of off the page — "P2P sync and reorg handling" was clipped. */
          ...(slot.x >= 70 ? { right: `${100 - slot.x}%` } : { left: `${slot.x}%` }),
          top: `${slot.y}%`,
          "--depth": String(slot.depth ?? 0.7),
        };
        const tag: TagStyle = {
          /* `rotate`, `translate` and `scale` are separate CSS properties, not one
             `transform` string. That is what lets the tilt sit here, the drift live in a
             keyframe, and the hover lift be a third rule — with one `transform` the last
             writer would win and hovering would snap the tag upright. */
          rotate: `${slot.rot}deg`,
          "--fs": `${((slot.scale ?? 1) * 14.5).toFixed(2)}px`,
          ...drift(i),
          "--rot": `${slot.rot}deg`,
        };
        return (
          <span className="sticker-plane" key={word} style={plane}>
            <button
              className="sticker"
              style={tag}
              onClick={() => onPick(`Tell me about his ${word} work.`)}
            >
              {word}
            </button>
          </span>
        );
      })}
    </div>
  );
}
