/* Keyword tags scattered around the landing page, tilted, taken from the SKILLS section of
 * the résumé (see keywords.generated.ts — regenerated by `npm run corpus`).
 *
 * Two decisions worth stating.
 *
 * The positions are hand-placed, not random. Random scatter looks the same on average and
 * occasionally drops a tag straight onto the composer, and a layout that is broken one visit
 * in ten is broken. Each slot is a percentage of the container with a fixed tilt, arranged in
 * two bands down the left and right of the centre column.
 *
 * They are buttons. A decoration that answers when you click it stops being decoration —
 * clicking "HTLC atomic swaps" asks about HTLC atomic swaps, which is also the fastest way to
 * discover that arbitrary questions work at all. They stay quiet until hovered so they read
 * as texture first and as an invitation second.
 */

import type React from "react";
import { RESUME_KEYWORDS } from "./keywords.generated";

interface Slot {
  /** Percentage from the left edge of the landing area. */
  x: number;
  /** Percentage from the top. */
  y: number;
  /** Degrees. */
  rot: number;
  /** Relative size, 0.9–1.1. */
  scale?: number;
}

/* Each tag drifts on its own loop. The numbers are the point of this: 16–26 seconds for one
 * circuit of 5–9 pixels is slow enough that you never catch a tag moving, only notice the
 * page is not quite still. Shared timings would make the whole set breathe in unison, which
 * reads as a loading state. Derived from the index so the arrangement stays deterministic. */
type TagStyle = React.CSSProperties & Record<`--${string}`, string>;

function drift(i: number): TagStyle {
  const dx = 5 + ((i * 3) % 5);
  const dy = 4 + ((i * 5) % 4);
  return {
    "--dx": `${i % 2 ? dx : -dx}px`,
    "--dy": `${i % 3 ? dy : -dy}px`,
    "--dur": `${16 + ((i * 7) % 11)}s`,
    "--lag": `-${(i * 1.9).toFixed(1)}s`,
  };
}

/* Left band, right band, and a few along the top and bottom. Nothing between x 26 and 74,
 * which is where the heading, the composer and the suggestion chips live. */
const SLOTS: Slot[] = [
  // Left band. Slots level with the centre column stay inside x 16, so even a long keyword
  // cannot reach the composer.
  { x: 6, y: 12, rot: -7 },
  { x: 5, y: 25, rot: 5, scale: 1.08 },
  { x: 3, y: 37, rot: 8 },
  { x: 4, y: 48, rot: -4 },
  { x: 6, y: 59, rot: 6, scale: 0.94 },
  { x: 14, y: 71, rot: -8 },
  { x: 8, y: 83, rot: 3 },

  // Right band, anchored on the right edge. Pulled to x 96–97 across the centre column's
  // height for the same reason, and only shorter keywords are placed there.
  { x: 82, y: 11, rot: 6 },
  { x: 96, y: 25, rot: -5, scale: 1.06 },
  { x: 97, y: 36, rot: -8 },
  { x: 96, y: 47, rot: 4 },
  { x: 97, y: 58, rot: -3, scale: 0.95 },
  { x: 92, y: 70, rot: 7 },
  { x: 82, y: 82, rot: -6 },

  // Above the heading and below the chips, where the column is clear.
  { x: 33, y: 7, rot: -4, scale: 0.94 },
  { x: 57, y: 5, rot: 5 },
  { x: 29, y: 90, rot: 6 },
  { x: 63, y: 91, rot: -5, scale: 0.96 },
];

/* Which keywords go in which slot. Fixed rather than shuffled: the page should look the same
 * every visit, and the interesting terms belong in the slots nearest the eye. */
const ORDER = [
  // Ordered to match SLOTS: the short terms take the slots level with the centre column,
  // where there is least room, and the long ones sit above or below it.
  "Rust",                        // left, high
  "HTLC atomic swaps",           // left, above the heading line
  "libvirt",                     // left, level with the heading
  "strace",                      // left, level with the composer
  "Virtio",                      // left, level with the chips
  "Model Context Protocol",      // left, below
  "UTXO ledgers",                // left, lowest
  "Linux kernel internals",      // right, high
  "P2P sync and reorg handling", // right, above the heading line
  "QEMU/KVM",                    // right, level with the heading
  "gdb",                         // right, level with the composer
  "perf",                        // right, level with the chips
  "QEMU Guest Agent",            // right, below
  "agent tool design",           // right, lowest
  "Python",                      // above the heading
  "TypeScript",
  "V2V migration",               // below the chips
  "LLM-as-judge",
];

export function Stickers({ onPick }: { onPick: (question: string) => void }) {
  const available = new Set<string>(RESUME_KEYWORDS);
  // Anything in ORDER that has left the résumé is dropped; anything new fills the gaps, so a
  // changed SKILLS section degrades into a different arrangement rather than blank slots.
  const chosen = [
    ...ORDER.filter((k) => available.has(k)),
    ...RESUME_KEYWORDS.filter((k) => !ORDER.includes(k)),
  ].slice(0, SLOTS.length);

  return (
    <div className="stickers" aria-label="Topics from his résumé">
      {chosen.map((word, i) => {
        const slot = SLOTS[i]!;
        const style: TagStyle = {
          /* Right-band tags anchor on their right edge so a long keyword grows inward
             instead of off the page — "P2P sync and reorg handling" was clipped. */
          ...(slot.x >= 70 ? { right: `${100 - slot.x}%` } : { left: `${slot.x}%` }),
          top: `${slot.y}%`,
          /* `rotate`, `translate` and `scale` are separate CSS properties, not one
             `transform` string. That is what lets the tilt sit here, the drift live in a
             keyframe, and the hover lift be a third rule — with one `transform` the last
             writer would win and hovering would snap the tag upright. */
          rotate: `${slot.rot}deg`,
          "--fs": `${((slot.scale ?? 1) * 14.5).toFixed(2)}px`,
          ...drift(i),
          "--rot": `${slot.rot}deg`,
        };
        return (
          <button
            key={word}
            className="sticker"
            style={style}
            onClick={() => onPick(`Tell me about his ${word} work.`)}
          >
            {word}
          </button>
        );
      })}
    </div>
  );
}
